global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cockroachdb'
    static_configs:
      - targets: ['cockroachdb-node1:8080', 'cockroachdb-node2:8080', 'cockroachdb-node3:8080']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ingestion-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['ingestion-worker:8000']
